# Generated by Django 3.1.7 on 2021-03-04 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210302_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='uploaded_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
