# Generated by Django 3.1.7 on 2021-03-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210312_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('Btech 1st', 'Btech 1st'), ('Btech 2nd', 'Btech 2nd'), ('Btech 3rd', 'Btech 3rd'), ('Btech 4th', 'Btech 4th'), ('Btech 5th', 'Btech 5th'), ('Btech 6th', 'Btech 6th'), ('Btech 7th', 'Btech 7th'), ('Btech 8th', 'Btech 8th')], max_length=10)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
            },
        ),
    ]
