# Generated by Django 3.1.7 on 2021-03-19 08:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.semester'),
            preserve_default=False,
        ),
    ]
