# Generated by Django 3.1.7 on 2021-03-21 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210319_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit', models.CharField(blank=True, choices=[('Unit 1', 'Unit 1'), ('Unit 2', 'Unit 2'), ('Unit 3', 'Unit 3'), ('Unit 4', 'Unit 4')], max_length=10, null=True)),
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.AlterField(
            model_name='semester',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='unit',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='accounts.unit'),
            preserve_default=False,
        ),
    ]
