# Generated by Django 3.1.7 on 2021-03-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210321_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
