# Generated by Django 3.1.7 on 2021-03-21 17:51

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210321_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='img',
            field=models.ImageField(default='', upload_to=accounts.models.unique_file_path),
        ),
    ]
